// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Writes `lib/src/examples.g.dart` from the v0.9 basic catalog examples in
/// the specification.
///
/// Run from the package directory after the examples change:
///
/// ```sh
/// dart run tool/generate_examples.dart
/// ```
///
/// `test/examples_test.dart` fails if the checked-in output is stale.
library;

import 'dart:convert';
import 'dart:io';

/// The examples directory, relative to the package directory.
const String examplesDirectory =
    '../../../specification/v0_9/catalogs/basic/examples';

/// The generated library, relative to the package directory.
const String outputFile = 'lib/src/examples.g.dart';

void main() {
  File(outputFile).writeAsStringSync(render(Directory(examplesDirectory)));
  stdout.writeln('Wrote $outputFile from $examplesDirectory.');
}

/// The generated library for the `.json` files in [directory], sorted by
/// file name.
String render(Directory directory) {
  final List<File> files =
      directory
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.json'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
  final buffer = StringBuffer(_header);
  for (final file in files) {
    final document =
        jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
    final String json = jsonEncode(document);
    if (json.contains("'''") || json.endsWith("'")) {
      throw StateError('${file.path} cannot be embedded in a raw string.');
    }
    buffer
      ..writeln('  Example(')
      ..writeln(_field('fileName', _literal(file.uri.pathSegments.last)))
      ..writeln(_field('name', _literal(document['name']! as String)))
      ..writeln(
        _field('description', _literal(document['description']! as String)),
      )
      ..writeln(_field('json', "r'''$json'''"))
      ..writeln('  ),');
  }
  buffer.writeln('];');
  return '$buffer';
}

/// The named argument [name] with the value [literal], split after the
/// colon when it does not fit in 80 columns, as `dart format` splits it.
String _field(String name, String literal) {
  final line = '    $name: $literal,';
  return line.length <= 80 ? line : '    $name:\n        $literal,';
}

/// [value] as a single-quoted Dart string literal.
String _literal(String value) {
  final String escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
  return "'$escaped'";
}

const String _header = '''
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by tool/generate_examples.dart from
// specification/v0_9/catalogs/basic/examples. Do not edit by hand. To
// regenerate, run `dart run tool/generate_examples.dart` from the package
// directory.

// ignore_for_file: lines_longer_than_80_chars

import 'example.dart';

/// The v0.9 basic catalog examples, sorted by file name.
const List<Example> examples = [
''';
