# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""A2UI Protocol v1.0 typesafe builder models and wire packaging helpers."""

from ..core import (
    OPEN_ENUM,
    OPEN_ENUM_CONTEXT,
    BuilderBaseModel,
    Child,
    ComponentBuilderNode,
    ComponentRef,
    ComponentTree,
    IdAllocator,
    flatten_component_tree,
)
from .models import (
    AccessibilityAttributes,
    Action,
    ActionEvent,
    CheckRule,
    ChildList,
    DataBinding,
    DynamicBoolean,
    DynamicChildList,
    DynamicNumber,
    DynamicString,
    DynamicStringList,
    DynamicValue,
    FunctionCall,
)
from . import catalogs as catalogs
from .catalogs import basic as basic
from .catalogs.basic import (
    And,
    AudioPlayer,
    Button,
    ButtonVariant,
    Card,
    CheckBox,
    ChoicePicker,
    ChoicePickerDisplayStyle,
    ChoicePickerOption,
    ChoicePickerVariant,
    Column,
    DateTimeInput,
    Divider,
    DividerAxis,
    Email,
    FlexAlign,
    FlexJustify,
    FormatCurrency,
    FormatDate,
    FormatNumber,
    FormatString,
    Icon,
    IconName,
    IconNameSvgPath,
    Image,
    ImageFit,
    ImageVariant,
    Length,
    List,
    ListAlign,
    ListDirection,
    Modal,
    Not,
    Numeric,
    OpenUrl,
    Or,
    Pluralize,
    Regex,
    Required,
    Row,
    Slider,
    TabItem,
    Tabs,
    Text,
    TextField,
    TextFieldVariant,
    TextVariant,
    Video,
)

__all__ = [
    "AccessibilityAttributes",
    "Action",
    "ActionEvent",
    "And",
    "AudioPlayer",
    "BuilderBaseModel",
    "Button",
    "ButtonVariant",
    "Card",
    "CheckBox",
    "CheckRule",
    "Child",
    "ChildList",
    "ChoicePicker",
    "ChoicePickerDisplayStyle",
    "ChoicePickerOption",
    "ChoicePickerVariant",
    "Column",
    "ComponentBuilderNode",
    "ComponentRef",
    "ComponentTree",
    "DataBinding",
    "DateTimeInput",
    "Divider",
    "DividerAxis",
    "DynamicBoolean",
    "DynamicChildList",
    "DynamicNumber",
    "DynamicString",
    "DynamicStringList",
    "DynamicValue",
    "Email",
    "FlexAlign",
    "FlexJustify",
    "FormatCurrency",
    "FormatDate",
    "FormatNumber",
    "FormatString",
    "FunctionCall",
    "Icon",
    "IconName",
    "IconNameSvgPath",
    "IdAllocator",
    "Image",
    "ImageFit",
    "ImageVariant",
    "Length",
    "List",
    "ListAlign",
    "ListDirection",
    "Modal",
    "Not",
    "Numeric",
    "OPEN_ENUM",
    "OPEN_ENUM_CONTEXT",
    "OpenUrl",
    "Or",
    "Pluralize",
    "Regex",
    "Required",
    "Row",
    "Slider",
    "TabItem",
    "Tabs",
    "Text",
    "TextField",
    "TextFieldVariant",
    "TextVariant",
    "Video",
    "basic",
    "catalogs",
    "flatten_component_tree",
]
