# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto-generated. Do not edit manually.
from __future__ import annotations

from .constants import *
from .common_types import (
    ComponentReference,
    SingleReference,
    ListReference,
    StrictBaseModel,
    ComponentId,
    Child,
    CallId,
    DataBinding,
    FunctionCall,
    DynamicValue,
    DynamicString,
    DynamicNumber,
    DynamicBoolean,
    DynamicStringList,
    TemplateChildList,
    ChildList,
    AccessibilityAttributes,
    FunctionCommon,
    IndexSystemFunctionArgs,
    IndexSystemFunction,
    CheckRule,
    Extensions,
    ActionEvent,
    ActionEventWrapper,
    ActionFunctionCallWrapper,
    Action,
    ComponentCommon,
    FunctionResponseError,
    FunctionResponse,
)
from .agent_to_renderer import (
    ComponentsList,
    Component,
    CreateSurface,
    CreateSurfaceMessage,
    UpdateComponents,
    UpdateComponentsMessage,
    UpdateDataModel,
    UpdateDataModelMessage,
    DeleteSurface,
    DeleteSurfaceMessage,
    CallRendererFunction,
    CallRendererFunctionMessage,
    AgentFunctionResponse,
    AgentFunctionResponseMessage,
    AgentToRendererMessage,
    AgentToRendererMessageList,
    AgentToRendererMessageListWrapper,
)
from .catalog_definition import (
    ValidationResult,
    ComponentDefinition,
    FunctionDefinition,
    CatalogDefs,
    CatalogDefinition,
)
from .renderer_capabilities import (
    InlineCatalog,
    Catalog,
    V10Capabilities,
    V1_0Capabilities,
    A2uiRendererCapabilities,
)
from .agent_capabilities import (
    V10AgentCapabilities,
    V1_0AgentCapabilities,
    A2uiAgentCapabilities,
)
from .renderer_to_agent import (
    A2uiRendererAction,
    ActionPayload,
    CallAgentFunction,
    A2uiValidationError,
    A2uiGenericError,
    A2uiRendererError,
    A2uiRendererActionMessage,
    CallAgentFunctionMessage,
    RendererFunctionResponseMessage,
    A2uiRendererErrorMessage,
    RendererToAgentMessage,
    A2uiRendererDataModel,
    RendererToAgentMessageList,
    RendererToAgentMessageListWrapper,
)


__all__ = [
    "ComponentReference",
    "SingleReference",
    "ListReference",
    "StrictBaseModel",
    "ComponentId",
    "Child",
    "CallId",
    "DataBinding",
    "FunctionCall",
    "DynamicValue",
    "DynamicString",
    "DynamicNumber",
    "DynamicBoolean",
    "DynamicStringList",
    "TemplateChildList",
    "ChildList",
    "AccessibilityAttributes",
    "FunctionCommon",
    "IndexSystemFunctionArgs",
    "IndexSystemFunction",
    "CheckRule",
    "Extensions",
    "ActionEvent",
    "ActionEventWrapper",
    "ActionFunctionCallWrapper",
    "Action",
    "ComponentCommon",
    "FunctionResponseError",
    "FunctionResponse",
    "ComponentsList",
    "Component",
    "CreateSurface",
    "CreateSurfaceMessage",
    "UpdateComponents",
    "UpdateComponentsMessage",
    "UpdateDataModel",
    "UpdateDataModelMessage",
    "DeleteSurface",
    "DeleteSurfaceMessage",
    "CallRendererFunction",
    "CallRendererFunctionMessage",
    "AgentFunctionResponse",
    "AgentFunctionResponseMessage",
    "AgentToRendererMessage",
    "AgentToRendererMessageList",
    "AgentToRendererMessageListWrapper",
    "ValidationResult",
    "ComponentDefinition",
    "FunctionDefinition",
    "CatalogDefs",
    "CatalogDefinition",
    "InlineCatalog",
    "Catalog",
    "V10Capabilities",
    "V1_0Capabilities",
    "A2uiRendererCapabilities",
    "V10AgentCapabilities",
    "V1_0AgentCapabilities",
    "A2uiAgentCapabilities",
    "A2uiRendererAction",
    "ActionPayload",
    "CallAgentFunction",
    "A2uiValidationError",
    "A2uiGenericError",
    "A2uiRendererError",
    "A2uiRendererActionMessage",
    "CallAgentFunctionMessage",
    "RendererFunctionResponseMessage",
    "A2uiRendererErrorMessage",
    "RendererToAgentMessage",
    "A2uiRendererDataModel",
    "RendererToAgentMessageList",
    "RendererToAgentMessageListWrapper",
]
