/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {AnalysedCatalog, AnalysedComponentApi, AnalysedFunctionApi} from '../../analyzer/types.js';
import {sanitizeIdent, typeToPython} from './type-mapper.js';

export const LICENSE_HEADER = `# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
`;

export interface PythonEmitterOptions {
  baseImport?: string;
}

export class PythonEmitter {
  readonly catalog: AnalysedCatalog;
  readonly baseImport: string;

  constructor(catalog: AnalysedCatalog, options: PythonEmitterOptions = {}) {
    this.catalog = catalog;
    this.baseImport =
      options.baseImport || 'a2ui.inference_formats.experimental.macros.builder.base';
  }

  emit(outputDir: string): string[] {
    fs.mkdirSync(outputDir, {recursive: true});
    const writtenFiles: string[] = [];

    // 1. types.py
    const typesPath = path.join(outputDir, 'types.py');
    fs.writeFileSync(typesPath, this.generateTypes(), 'utf-8');
    writtenFiles.push(typesPath);

    // 2. components.py
    const compPath = path.join(outputDir, 'components.py');
    fs.writeFileSync(compPath, this.generateComponents(), 'utf-8');
    writtenFiles.push(compPath);

    // 3. functions.py
    const fnPath = path.join(outputDir, 'functions.py');
    fs.writeFileSync(fnPath, this.generateFunctions(), 'utf-8');
    writtenFiles.push(fnPath);

    // 4. __init__.py
    const initPath = path.join(outputDir, '__init__.py');
    fs.writeFileSync(initPath, this.generateInit(), 'utf-8');
    writtenFiles.push(initPath);

    // 5. py.typed
    const typedPath = path.join(outputDir, 'py.typed');
    fs.writeFileSync(typedPath, '', 'utf-8');
    writtenFiles.push(typedPath);

    return writtenFiles;
  }

  generateTypes(): string {
    const lines: string[] = [
      LICENSE_HEADER.trim(),
      '',
      '# Generated by @a2ui/cli. DO NOT EDIT DIRECTLY.',
      '"""String literal enums for the catalog."""',
      '',
      'from typing import Literal',
      '',
      '',
    ];

    for (const [enumName, enumDesc] of this.catalog.enums.entries()) {
      const vals = enumDesc.values.map(v => `"${v}"`).join(', ');
      lines.push(`${enumName} = Literal[${vals}]`);
    }

    lines.push('');
    const allExports = Array.from(this.catalog.enums.keys())
      .map(e => `"${e}"`)
      .join(', ');
    lines.push(`__all__ = [${allExports}]`);
    lines.push('');
    return lines.join('\n');
  }

  generateComponents(): string {
    const lines: string[] = [
      LICENSE_HEADER.trim(),
      '',
      '# Generated by @a2ui/cli. DO NOT EDIT DIRECTLY.',
      '"""Typesafe A2UI component definitions."""',
      '',
      'from dataclasses import dataclass, field',
      'from typing import Any, Mapping, Optional, Sequence, Union',
      '',
      `from ${this.baseImport} import (`,
      '    Action,',
      '    CheckRule,',
      '    ComponentBuilderNode,',
      '    DataBinding,',
      '    DynamicChildList,',
      '    FunctionCall,',
      ')',
      'from .types import *',
      '',
      '',
      'def _serialize_prop(val: Any) -> Any:',
      '    if hasattr(val, "to_dict"):',
      '        return val.to_dict()',
      '    if isinstance(val, (list, tuple)):',
      '        return [_serialize_prop(item) for item in val]',
      '    return val',
      '',
      '',
    ];

    for (const comp of this.catalog.components.values()) {
      lines.push(this.generateComponentClass(comp));
      lines.push('');
    }

    const compNames = Array.from(this.catalog.components.keys()).map(c => `"${c}"`);
    lines.push(`__all__ = [${compNames.join(', ')}]`);
    lines.push('');
    return lines.join('\n');
  }

  private generateComponentClass(comp: AnalysedComponentApi): string {
    const lines: string[] = [
      '@dataclass(kw_only=True)',
      `class ${comp.name}(ComponentBuilderNode):`,
    ];

    const doc = comp.description || `${comp.name} component.`;
    lines.push(`    r"""${doc}"""`);
    lines.push('');
    lines.push(`    component_name: str = field(default="${comp.name}", init=False)`);

    for (const [pName, prop] of comp.properties.entries()) {
      if (pName === 'component') continue;
      const pyName = sanitizeIdent(pName);
      const pyType = typeToPython(prop.type);

      if (prop.isRequired) {
        lines.push(`    ${pyName}: ${pyType}`);
      } else {
        let defaultStr = 'None';
        if (prop.defaultValue !== undefined) {
          if (typeof prop.defaultValue === 'string') {
            defaultStr = `"${prop.defaultValue}"`;
          } else if (typeof prop.defaultValue === 'boolean') {
            defaultStr = prop.defaultValue ? 'True' : 'False';
          } else if (typeof prop.defaultValue === 'number') {
            defaultStr = String(prop.defaultValue);
          }
        }
        lines.push(`    ${pyName}: Optional[${pyType}] = ${defaultStr}`);
      }
    }

    lines.push('');
    // to_dict
    lines.push('    def to_dict(self) -> dict[str, Any]:');
    lines.push('        d: dict[str, Any] = {"component": self.component_name}');
    for (const pName of comp.properties.keys()) {
      if (pName === 'component' || pName === 'id') continue;
      const pyName = sanitizeIdent(pName);
      lines.push(`        if self.${pyName} is not None:`);
      lines.push(`            d["${pName}"] = _serialize_prop(self.${pyName})`);
    }
    lines.push('        if self.id is not None:');
    lines.push('            d["id"] = self.id');
    lines.push('        return d');

    return lines.join('\n');
  }

  generateFunctions(): string {
    const lines: string[] = [
      LICENSE_HEADER.trim(),
      '',
      '# Generated by @a2ui/cli. DO NOT EDIT DIRECTLY.',
      '"""Typesafe catalog function wrappers."""',
      '',
      'from typing import Any, Mapping, Optional, Sequence, Union',
      '',
      `from ${this.baseImport} import DataBinding, FunctionCall`,
      'from .types import *',
      '',
      '',
    ];

    for (const fn of this.catalog.functions.values()) {
      lines.push(this.generateFunctionDef(fn));
      lines.push('');
    }

    const fnNames = Array.from(this.catalog.functions.keys()).map(f => `"${sanitizeIdent(f)}"`);
    lines.push(`__all__ = [${fnNames.join(', ')}]`);
    lines.push('');
    return lines.join('\n');
  }

  private generateFunctionDef(fn: AnalysedFunctionApi): string {
    const paramSigs: string[] = ['*'];
    const argsDictItems: string[] = [];
    const pyFnName = sanitizeIdent(fn.name);

    for (const [pName, pDesc] of fn.parameters.entries()) {
      const pyParam = sanitizeIdent(pName);
      const pyType = typeToPython(pDesc.type);
      if (pDesc.isRequired) {
        paramSigs.push(`${pyParam}: ${pyType}`);
      } else {
        paramSigs.push(`${pyParam}: Optional[${pyType}] = None`);
      }
      argsDictItems.push(
        `    if ${pyParam} is not None:\n        args["${pName}"] = ${pyParam}.to_dict() if hasattr(${pyParam}, "to_dict") else ${pyParam}`,
      );
    }

    paramSigs.push('call_id: Optional[str] = None');
    const paramsStr = paramSigs.join(', ');

    const doc = fn.description || `Invokes catalog function ${fn.name}.`;
    const lines: string[] = [
      `def ${pyFnName}(${paramsStr}) -> FunctionCall:`,
      `    r"""${doc}"""`,
      '    args: dict[str, Any] = {}',
    ];
    if (argsDictItems.length > 0) {
      lines.push(argsDictItems.join('\n'));
    }
    lines.push(`    return FunctionCall(call="${fn.name}", args=args, call_id=call_id)`);

    return lines.join('\n');
  }

  generateInit(): string {
    const lines: string[] = [
      LICENSE_HEADER.trim(),
      '',
      '# Generated by @a2ui/cli. DO NOT EDIT DIRECTLY.',
      '"""A2UI Typesafe Catalog package."""',
      '',
      `from ${this.baseImport} import (`,
      '    Action,',
      '    CheckRule,',
      '    ComponentBuilderNode,',
      '    ComponentRef,',
      '    DataBinding,',
      '    DynamicChildList,',
      '    ExternalComponentBuilderNode,',
      '    FunctionCall,',
      '    IdAllocator,',
      '    Surface,',
      '    bind,',
      '    flatten_component_tree,',
      ')',
      'from .components import *',
      'from .functions import *',
      'from .types import *',
      '',
    ];
    return lines.join('\n');
  }
}
