# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by a2ui-codegen. DO NOT EDIT DIRECTLY.
"""Typesafe A2UI component definitions."""

from dataclasses import dataclass, field
from typing import Any, Mapping, Optional, Sequence, Union

from a2ui.inference_formats.experimental.macros.builder.base import (
    Action,
    CheckRule,
    ComponentBuilderNode,
    DataBinding,
    DynamicChildList,
    FunctionCall,
)
from .types import *


@dataclass(kw_only=True)
class Text(ComponentBuilderNode):
    r"""Text component."""

    component_name: str = field(default="Text", init=False)
    text: str | DataBinding | FunctionCall
    variant: Optional[TextVariant] = "body"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.text is not None:
            d["text"] = self.text.to_dict() if hasattr(self.text, "to_dict") else self.text
        if self.variant is not None:
            d["variant"] = self.variant.to_dict() if hasattr(self.variant, "to_dict") else self.variant
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Image(ComponentBuilderNode):
    r"""Image component."""

    component_name: str = field(default="Image", init=False)
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    fit: Optional[ImageFit] = "fill"
    variant: Optional[ImageVariant] = "mediumFeature"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.url is not None:
            d["url"] = self.url.to_dict() if hasattr(self.url, "to_dict") else self.url
        if self.description is not None:
            d["description"] = self.description.to_dict() if hasattr(self.description, "to_dict") else self.description
        if self.fit is not None:
            d["fit"] = self.fit.to_dict() if hasattr(self.fit, "to_dict") else self.fit
        if self.variant is not None:
            d["variant"] = self.variant.to_dict() if hasattr(self.variant, "to_dict") else self.variant
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Icon(ComponentBuilderNode):
    r"""Icon component."""

    component_name: str = field(default="Icon", init=False)
    name: IconName | DataBinding | FunctionCall
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.name is not None:
            d["name"] = self.name.to_dict() if hasattr(self.name, "to_dict") else self.name
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Video(ComponentBuilderNode):
    r"""Video component."""

    component_name: str = field(default="Video", init=False)
    url: str | DataBinding | FunctionCall
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.url is not None:
            d["url"] = self.url.to_dict() if hasattr(self.url, "to_dict") else self.url
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class AudioPlayer(ComponentBuilderNode):
    r"""AudioPlayer component."""

    component_name: str = field(default="AudioPlayer", init=False)
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.url is not None:
            d["url"] = self.url.to_dict() if hasattr(self.url, "to_dict") else self.url
        if self.description is not None:
            d["description"] = self.description.to_dict() if hasattr(self.description, "to_dict") else self.description
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Row(ComponentBuilderNode):
    r"""Row component."""

    component_name: str = field(default="Row", init=False)
    children: Sequence[ComponentBuilderNode] | DynamicChildList
    align: Optional[FlexAlign] = "stretch"
    justify: Optional[FlexJustify] = "start"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.children is not None:
            d["children"] = self.children.to_dict() if hasattr(self.children, "to_dict") else self.children
        if self.align is not None:
            d["align"] = self.align.to_dict() if hasattr(self.align, "to_dict") else self.align
        if self.justify is not None:
            d["justify"] = self.justify.to_dict() if hasattr(self.justify, "to_dict") else self.justify
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Column(ComponentBuilderNode):
    r"""Column component."""

    component_name: str = field(default="Column", init=False)
    children: Sequence[ComponentBuilderNode] | DynamicChildList
    align: Optional[FlexAlign] = "stretch"
    justify: Optional[FlexJustify] = "start"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.children is not None:
            d["children"] = self.children.to_dict() if hasattr(self.children, "to_dict") else self.children
        if self.align is not None:
            d["align"] = self.align.to_dict() if hasattr(self.align, "to_dict") else self.align
        if self.justify is not None:
            d["justify"] = self.justify.to_dict() if hasattr(self.justify, "to_dict") else self.justify
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class List(ComponentBuilderNode):
    r"""List component."""

    component_name: str = field(default="List", init=False)
    children: Sequence[ComponentBuilderNode] | DynamicChildList
    align: Optional[ListAlign] = "stretch"
    direction: Optional[ListDirection] = "vertical"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.children is not None:
            d["children"] = self.children.to_dict() if hasattr(self.children, "to_dict") else self.children
        if self.align is not None:
            d["align"] = self.align.to_dict() if hasattr(self.align, "to_dict") else self.align
        if self.direction is not None:
            d["direction"] = self.direction.to_dict() if hasattr(self.direction, "to_dict") else self.direction
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Card(ComponentBuilderNode):
    r"""Card component."""

    component_name: str = field(default="Card", init=False)
    child: ComponentBuilderNode
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.child is not None:
            d["child"] = self.child.to_dict() if hasattr(self.child, "to_dict") else self.child
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Tabs(ComponentBuilderNode):
    r"""Tabs component."""

    component_name: str = field(default="Tabs", init=False)
    tabs: Sequence[Mapping[str, Any]]
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.tabs is not None:
            d["tabs"] = self.tabs.to_dict() if hasattr(self.tabs, "to_dict") else self.tabs
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Modal(ComponentBuilderNode):
    r"""Modal component."""

    component_name: str = field(default="Modal", init=False)
    content: ComponentBuilderNode
    trigger: ComponentBuilderNode
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.content is not None:
            d["content"] = self.content.to_dict() if hasattr(self.content, "to_dict") else self.content
        if self.trigger is not None:
            d["trigger"] = self.trigger.to_dict() if hasattr(self.trigger, "to_dict") else self.trigger
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Divider(ComponentBuilderNode):
    r"""Divider component."""

    component_name: str = field(default="Divider", init=False)
    axis: Optional[DividerAxis] = "horizontal"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.axis is not None:
            d["axis"] = self.axis.to_dict() if hasattr(self.axis, "to_dict") else self.axis
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Button(ComponentBuilderNode):
    r"""Button component."""

    component_name: str = field(default="Button", init=False)
    action: Action
    child: ComponentBuilderNode
    checks: Optional[Sequence[CheckRule]] = None
    variant: Optional[ButtonVariant] = "default"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.action is not None:
            d["action"] = self.action.to_dict() if hasattr(self.action, "to_dict") else self.action
        if self.child is not None:
            d["child"] = self.child.to_dict() if hasattr(self.child, "to_dict") else self.child
        if self.checks is not None:
            d["checks"] = self.checks.to_dict() if hasattr(self.checks, "to_dict") else self.checks
        if self.variant is not None:
            d["variant"] = self.variant.to_dict() if hasattr(self.variant, "to_dict") else self.variant
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class TextField(ComponentBuilderNode):
    r"""TextField component."""

    component_name: str = field(default="TextField", init=False)
    label: str | DataBinding | FunctionCall
    checks: Optional[Sequence[CheckRule]] = None
    validationRegexp: Optional[str] = None
    value: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[TextFieldVariant] = "shortText"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.label is not None:
            d["label"] = self.label.to_dict() if hasattr(self.label, "to_dict") else self.label
        if self.checks is not None:
            d["checks"] = self.checks.to_dict() if hasattr(self.checks, "to_dict") else self.checks
        if self.validationRegexp is not None:
            d["validationRegexp"] = self.validationRegexp.to_dict() if hasattr(self.validationRegexp, "to_dict") else self.validationRegexp
        if self.value is not None:
            d["value"] = self.value.to_dict() if hasattr(self.value, "to_dict") else self.value
        if self.variant is not None:
            d["variant"] = self.variant.to_dict() if hasattr(self.variant, "to_dict") else self.variant
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class CheckBox(ComponentBuilderNode):
    r"""CheckBox component."""

    component_name: str = field(default="CheckBox", init=False)
    label: str | DataBinding | FunctionCall
    value: bool | DataBinding | FunctionCall
    checks: Optional[Sequence[CheckRule]] = None
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.label is not None:
            d["label"] = self.label.to_dict() if hasattr(self.label, "to_dict") else self.label
        if self.value is not None:
            d["value"] = self.value.to_dict() if hasattr(self.value, "to_dict") else self.value
        if self.checks is not None:
            d["checks"] = self.checks.to_dict() if hasattr(self.checks, "to_dict") else self.checks
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class ChoicePicker(ComponentBuilderNode):
    r"""ChoicePicker component."""

    component_name: str = field(default="ChoicePicker", init=False)
    options: Sequence[Mapping[str, Any]]
    value: str | DataBinding | FunctionCall
    checks: Optional[Sequence[CheckRule]] = None
    displayStyle: Optional[ChoicePickerDisplaystyle] = "checkbox"
    filterable: Optional[bool] = False
    label: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[ChoicePickerVariant] = "mutuallyExclusive"
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.options is not None:
            d["options"] = self.options.to_dict() if hasattr(self.options, "to_dict") else self.options
        if self.value is not None:
            d["value"] = self.value.to_dict() if hasattr(self.value, "to_dict") else self.value
        if self.checks is not None:
            d["checks"] = self.checks.to_dict() if hasattr(self.checks, "to_dict") else self.checks
        if self.displayStyle is not None:
            d["displayStyle"] = self.displayStyle.to_dict() if hasattr(self.displayStyle, "to_dict") else self.displayStyle
        if self.filterable is not None:
            d["filterable"] = self.filterable.to_dict() if hasattr(self.filterable, "to_dict") else self.filterable
        if self.label is not None:
            d["label"] = self.label.to_dict() if hasattr(self.label, "to_dict") else self.label
        if self.variant is not None:
            d["variant"] = self.variant.to_dict() if hasattr(self.variant, "to_dict") else self.variant
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Slider(ComponentBuilderNode):
    r"""Slider component."""

    component_name: str = field(default="Slider", init=False)
    max: float
    value: float | DataBinding | FunctionCall
    checks: Optional[Sequence[CheckRule]] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    min: Optional[float] = 0
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.max is not None:
            d["max"] = self.max.to_dict() if hasattr(self.max, "to_dict") else self.max
        if self.value is not None:
            d["value"] = self.value.to_dict() if hasattr(self.value, "to_dict") else self.value
        if self.checks is not None:
            d["checks"] = self.checks.to_dict() if hasattr(self.checks, "to_dict") else self.checks
        if self.label is not None:
            d["label"] = self.label.to_dict() if hasattr(self.label, "to_dict") else self.label
        if self.min is not None:
            d["min"] = self.min.to_dict() if hasattr(self.min, "to_dict") else self.min
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class DateTimeInput(ComponentBuilderNode):
    r"""DateTimeInput component."""

    component_name: str = field(default="DateTimeInput", init=False)
    value: str | DataBinding | FunctionCall
    checks: Optional[Sequence[CheckRule]] = None
    enableDate: Optional[bool] = False
    enableTime: Optional[bool] = False
    label: Optional[str | DataBinding | FunctionCall] = None
    max: Optional[Any] = None
    min: Optional[Any] = None
    id: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.value is not None:
            d["value"] = self.value.to_dict() if hasattr(self.value, "to_dict") else self.value
        if self.checks is not None:
            d["checks"] = self.checks.to_dict() if hasattr(self.checks, "to_dict") else self.checks
        if self.enableDate is not None:
            d["enableDate"] = self.enableDate.to_dict() if hasattr(self.enableDate, "to_dict") else self.enableDate
        if self.enableTime is not None:
            d["enableTime"] = self.enableTime.to_dict() if hasattr(self.enableTime, "to_dict") else self.enableTime
        if self.label is not None:
            d["label"] = self.label.to_dict() if hasattr(self.label, "to_dict") else self.label
        if self.max is not None:
            d["max"] = self.max.to_dict() if hasattr(self.max, "to_dict") else self.max
        if self.min is not None:
            d["min"] = self.min.to_dict() if hasattr(self.min, "to_dict") else self.min
        if self.id is not None:
            d["id"] = self.id
        return d

__all__ = ["Text", "Image", "Icon", "Video", "AudioPlayer", "Row", "Column", "List", "Card", "Tabs", "Modal", "Divider", "Button", "TextField", "CheckBox", "ChoicePicker", "Slider", "DateTimeInput"]
