# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by @a2ui/cli. DO NOT EDIT DIRECTLY.
"""Typesafe A2UI component definitions."""

from dataclasses import dataclass, field
from typing import Any, Mapping, Optional, Sequence, Union

from a2ui.inference_formats.experimental.macros.builder.base import (
    Action,
    CheckRule,
    ComponentBuilderNode,
    DataBinding,
    DynamicChildList,
    FunctionCall,
)
from .types import *


def _serialize_prop(val: Any) -> Any:
    if hasattr(val, "to_dict"):
        return val.to_dict()
    if isinstance(val, (list, tuple)):
        return [_serialize_prop(item) for item in val]
    return val


@dataclass(kw_only=True)
class Text(ComponentBuilderNode):
    r"""Text component."""

    component_name: str = field(default="Text", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    text: str | DataBinding | FunctionCall
    variant: Optional[TextVariant] = "body"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.text is not None:
            d["text"] = _serialize_prop(self.text)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Image(ComponentBuilderNode):
    r"""Image component."""

    component_name: str = field(default="Image", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None
    fit: Optional[ImageFit] = "fill"
    variant: Optional[ImageVariant] = "mediumFeature"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.url is not None:
            d["url"] = _serialize_prop(self.url)
        if self.description is not None:
            d["description"] = _serialize_prop(self.description)
        if self.fit is not None:
            d["fit"] = _serialize_prop(self.fit)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Icon(ComponentBuilderNode):
    r"""Icon component."""

    component_name: str = field(default="Icon", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    name: IconName

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.name is not None:
            d["name"] = _serialize_prop(self.name)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Video(ComponentBuilderNode):
    r"""Video component."""

    component_name: str = field(default="Video", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.url is not None:
            d["url"] = _serialize_prop(self.url)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class AudioPlayer(ComponentBuilderNode):
    r"""AudioPlayer component."""

    component_name: str = field(default="AudioPlayer", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    url: str | DataBinding | FunctionCall
    description: Optional[str | DataBinding | FunctionCall] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.url is not None:
            d["url"] = _serialize_prop(self.url)
        if self.description is not None:
            d["description"] = _serialize_prop(self.description)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Row(ComponentBuilderNode):
    r"""Row component."""

    component_name: str = field(default="Row", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: Sequence[ComponentBuilderNode] | DynamicChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.children is not None:
            d["children"] = _serialize_prop(self.children)
        if self.justify is not None:
            d["justify"] = _serialize_prop(self.justify)
        if self.align is not None:
            d["align"] = _serialize_prop(self.align)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Column(ComponentBuilderNode):
    r"""Column component."""

    component_name: str = field(default="Column", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: Sequence[ComponentBuilderNode] | DynamicChildList
    justify: Optional[FlexJustify] = "start"
    align: Optional[FlexAlign] = "stretch"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.children is not None:
            d["children"] = _serialize_prop(self.children)
        if self.justify is not None:
            d["justify"] = _serialize_prop(self.justify)
        if self.align is not None:
            d["align"] = _serialize_prop(self.align)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class List(ComponentBuilderNode):
    r"""List component."""

    component_name: str = field(default="List", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    children: Sequence[ComponentBuilderNode] | DynamicChildList
    direction: Optional[ListDirection] = "vertical"
    align: Optional[ListAlign] = "stretch"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.children is not None:
            d["children"] = _serialize_prop(self.children)
        if self.direction is not None:
            d["direction"] = _serialize_prop(self.direction)
        if self.align is not None:
            d["align"] = _serialize_prop(self.align)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Card(ComponentBuilderNode):
    r"""Card component."""

    component_name: str = field(default="Card", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    child: ComponentBuilderNode

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.child is not None:
            d["child"] = _serialize_prop(self.child)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Tabs(ComponentBuilderNode):
    r"""Tabs component."""

    component_name: str = field(default="Tabs", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    tabs: Sequence[Mapping[str, Any]]

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.tabs is not None:
            d["tabs"] = _serialize_prop(self.tabs)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Modal(ComponentBuilderNode):
    r"""Modal component."""

    component_name: str = field(default="Modal", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    trigger: ComponentBuilderNode
    content: ComponentBuilderNode

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.trigger is not None:
            d["trigger"] = _serialize_prop(self.trigger)
        if self.content is not None:
            d["content"] = _serialize_prop(self.content)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Divider(ComponentBuilderNode):
    r"""Divider component."""

    component_name: str = field(default="Divider", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    axis: Optional[DividerAxis] = "horizontal"

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.axis is not None:
            d["axis"] = _serialize_prop(self.axis)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Button(ComponentBuilderNode):
    r"""Button component."""

    component_name: str = field(default="Button", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    child: ComponentBuilderNode
    variant: Optional[ButtonVariant] = "default"
    action: Action

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.child is not None:
            d["child"] = _serialize_prop(self.child)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.action is not None:
            d["action"] = _serialize_prop(self.action)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class TextField(ComponentBuilderNode):
    r"""TextField component."""

    component_name: str = field(default="TextField", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[TextFieldVariant] = "shortText"
    validationRegexp: Optional[str] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.validationRegexp is not None:
            d["validationRegexp"] = _serialize_prop(self.validationRegexp)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class CheckBox(ComponentBuilderNode):
    r"""CheckBox component."""

    component_name: str = field(default="CheckBox", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: str | DataBinding | FunctionCall
    value: bool | DataBinding | FunctionCall

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class ChoicePicker(ComponentBuilderNode):
    r"""ChoicePicker component."""

    component_name: str = field(default="ChoicePicker", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    variant: Optional[ChoicePickerVariant] = "mutuallyExclusive"
    options: Sequence[Mapping[str, Any]]
    value: Sequence[str] | DataBinding | FunctionCall
    displayStyle: Optional[ChoicePickerDisplayStyle] = "checkbox"
    filterable: Optional[bool] = False

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.variant is not None:
            d["variant"] = _serialize_prop(self.variant)
        if self.options is not None:
            d["options"] = _serialize_prop(self.options)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.displayStyle is not None:
            d["displayStyle"] = _serialize_prop(self.displayStyle)
        if self.filterable is not None:
            d["filterable"] = _serialize_prop(self.filterable)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class Slider(ComponentBuilderNode):
    r"""Slider component."""

    component_name: str = field(default="Slider", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    label: Optional[str | DataBinding | FunctionCall] = None
    min: Optional[float] = 0
    max: float
    value: float | DataBinding | FunctionCall

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.min is not None:
            d["min"] = _serialize_prop(self.min)
        if self.max is not None:
            d["max"] = _serialize_prop(self.max)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.id is not None:
            d["id"] = self.id
        return d

@dataclass(kw_only=True)
class DateTimeInput(ComponentBuilderNode):
    r"""DateTimeInput component."""

    component_name: str = field(default="DateTimeInput", init=False)
    accessibility: Optional[Any] = None
    weight: Optional[float] = None
    value: str | DataBinding | FunctionCall
    enableDate: Optional[bool] = False
    enableTime: Optional[bool] = False
    min: Optional[Any] = None
    max: Optional[Any] = None
    label: Optional[str | DataBinding | FunctionCall] = None

    def to_dict(self) -> dict[str, Any]:
        d: dict[str, Any] = {"component": self.component_name}
        if self.accessibility is not None:
            d["accessibility"] = _serialize_prop(self.accessibility)
        if self.weight is not None:
            d["weight"] = _serialize_prop(self.weight)
        if self.value is not None:
            d["value"] = _serialize_prop(self.value)
        if self.enableDate is not None:
            d["enableDate"] = _serialize_prop(self.enableDate)
        if self.enableTime is not None:
            d["enableTime"] = _serialize_prop(self.enableTime)
        if self.min is not None:
            d["min"] = _serialize_prop(self.min)
        if self.max is not None:
            d["max"] = _serialize_prop(self.max)
        if self.label is not None:
            d["label"] = _serialize_prop(self.label)
        if self.id is not None:
            d["id"] = self.id
        return d

__all__ = ["Text", "Image", "Icon", "Video", "AudioPlayer", "Row", "Column", "List", "Card", "Tabs", "Modal", "Divider", "Button", "TextField", "CheckBox", "ChoicePicker", "Slider", "DateTimeInput"]
