# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by a2ui-codegen. DO NOT EDIT DIRECTLY.
"""Typesafe catalog function wrappers."""

from typing import Any, Mapping, Optional, Sequence, Union

from a2ui.inference_formats.experimental.macros.builder.base import DataBinding, FunctionCall
from .types import *


def required(*, value: Any, call_id: Optional[str] = None) -> FunctionCall:
    r"""Checks that the value is not null, undefined, or empty."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="required", args=args, call_id=call_id)

def regex(*, value: str | DataBinding | FunctionCall, pattern: str, call_id: Optional[str] = None) -> FunctionCall:
    r"""Checks that the value matches a regular expression string."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if pattern is not None:
        args["pattern"] = pattern.to_dict() if hasattr(pattern, "to_dict") else pattern
    return FunctionCall(call="regex", args=args, call_id=call_id)

def length(*, value: str | DataBinding | FunctionCall, min: Optional[int] = None, max: Optional[int] = None, call_id: Optional[str] = None) -> FunctionCall:
    r"""Checks string length constraints."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if min is not None:
        args["min"] = min.to_dict() if hasattr(min, "to_dict") else min
    if max is not None:
        args["max"] = max.to_dict() if hasattr(max, "to_dict") else max
    return FunctionCall(call="length", args=args, call_id=call_id)

def numeric(*, value: float | DataBinding | FunctionCall, min: Optional[float] = None, max: Optional[float] = None, call_id: Optional[str] = None) -> FunctionCall:
    r"""Checks numeric range constraints."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if min is not None:
        args["min"] = min.to_dict() if hasattr(min, "to_dict") else min
    if max is not None:
        args["max"] = max.to_dict() if hasattr(max, "to_dict") else max
    return FunctionCall(call="numeric", args=args, call_id=call_id)

def email(*, value: str | DataBinding | FunctionCall, call_id: Optional[str] = None) -> FunctionCall:
    r"""Checks that the value is a valid email address."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="email", args=args, call_id=call_id)

def formatString(*, value: str | DataBinding | FunctionCall, call_id: Optional[str] = None) -> FunctionCall:
    r"""Performs string interpolation of data model values and other functions in the catalog functions list and returns the resulting string. The value string can contain interpolated expressions in the `${expression}` format. Supported expression types include: JSON Pointer paths to the data model (e.g., `${/absolute/path}` or `${relative/path}`), and client-side function calls (e.g., `${now()}`). Function arguments must be named (e.g., `${formatDate(value:${/currentDate}, format:'MM-dd')}`). To include a literal `${` sequence, escape it as `\${`."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="formatString", args=args, call_id=call_id)

def formatNumber(*, value: float | DataBinding | FunctionCall, decimals: Optional[float | DataBinding | FunctionCall] = None, grouping: Optional[bool | DataBinding | FunctionCall] = None, call_id: Optional[str] = None) -> FunctionCall:
    r"""Formats a number with the specified grouping and decimal precision."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if decimals is not None:
        args["decimals"] = decimals.to_dict() if hasattr(decimals, "to_dict") else decimals
    if grouping is not None:
        args["grouping"] = grouping.to_dict() if hasattr(grouping, "to_dict") else grouping
    return FunctionCall(call="formatNumber", args=args, call_id=call_id)

def formatCurrency(*, value: float | DataBinding | FunctionCall, currency: str | DataBinding | FunctionCall, decimals: Optional[float | DataBinding | FunctionCall] = None, grouping: Optional[bool | DataBinding | FunctionCall] = None, call_id: Optional[str] = None) -> FunctionCall:
    r"""Formats a number as a currency string."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if currency is not None:
        args["currency"] = currency.to_dict() if hasattr(currency, "to_dict") else currency
    if decimals is not None:
        args["decimals"] = decimals.to_dict() if hasattr(decimals, "to_dict") else decimals
    if grouping is not None:
        args["grouping"] = grouping.to_dict() if hasattr(grouping, "to_dict") else grouping
    return FunctionCall(call="formatCurrency", args=args, call_id=call_id)

def formatDate(*, value: Any | DataBinding | FunctionCall, format: str | DataBinding | FunctionCall, call_id: Optional[str] = None) -> FunctionCall:
    r"""Formats a timestamp into a string using a pattern."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if format is not None:
        args["format"] = format.to_dict() if hasattr(format, "to_dict") else format
    return FunctionCall(call="formatDate", args=args, call_id=call_id)

def pluralize(*, value: float | DataBinding | FunctionCall, zero: Optional[str | DataBinding | FunctionCall] = None, one: Optional[str | DataBinding | FunctionCall] = None, two: Optional[str | DataBinding | FunctionCall] = None, few: Optional[str | DataBinding | FunctionCall] = None, many: Optional[str | DataBinding | FunctionCall] = None, other: str | DataBinding | FunctionCall, call_id: Optional[str] = None) -> FunctionCall:
    r"""Returns a localized string based on the Common Locale Data Repository (CLDR) plural category of the count (zero, one, two, few, many, other). Requires an 'other' fallback. For English, just use 'one' and 'other'."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    if zero is not None:
        args["zero"] = zero.to_dict() if hasattr(zero, "to_dict") else zero
    if one is not None:
        args["one"] = one.to_dict() if hasattr(one, "to_dict") else one
    if two is not None:
        args["two"] = two.to_dict() if hasattr(two, "to_dict") else two
    if few is not None:
        args["few"] = few.to_dict() if hasattr(few, "to_dict") else few
    if many is not None:
        args["many"] = many.to_dict() if hasattr(many, "to_dict") else many
    if other is not None:
        args["other"] = other.to_dict() if hasattr(other, "to_dict") else other
    return FunctionCall(call="pluralize", args=args, call_id=call_id)

def openUrl(*, url: str, call_id: Optional[str] = None) -> FunctionCall:
    r"""Opens the specified URL in a browser or handler. This function has no return value."""
    args: dict[str, Any] = {}
    if url is not None:
        args["url"] = url.to_dict() if hasattr(url, "to_dict") else url
    return FunctionCall(call="openUrl", args=args, call_id=call_id)

def and_(*, values: Sequence[bool | DataBinding | FunctionCall], call_id: Optional[str] = None) -> FunctionCall:
    r"""Performs a logical AND operation on a list of boolean values."""
    args: dict[str, Any] = {}
    if values is not None:
        args["values"] = values.to_dict() if hasattr(values, "to_dict") else values
    return FunctionCall(call="and", args=args, call_id=call_id)

def or_(*, values: Sequence[bool | DataBinding | FunctionCall], call_id: Optional[str] = None) -> FunctionCall:
    r"""Performs a logical OR operation on a list of boolean values."""
    args: dict[str, Any] = {}
    if values is not None:
        args["values"] = values.to_dict() if hasattr(values, "to_dict") else values
    return FunctionCall(call="or", args=args, call_id=call_id)

def not_(*, value: bool | DataBinding | FunctionCall, call_id: Optional[str] = None) -> FunctionCall:
    r"""Performs a logical NOT operation on a boolean value."""
    args: dict[str, Any] = {}
    if value is not None:
        args["value"] = value.to_dict() if hasattr(value, "to_dict") else value
    return FunctionCall(call="not", args=args, call_id=call_id)

__all__ = ["required", "regex", "length", "numeric", "email", "formatString", "formatNumber", "formatCurrency", "formatDate", "pluralize", "openUrl", "and_", "or_", "not_"]
