# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by a2ui-codegen. DO NOT EDIT DIRECTLY.
"""String literal enums for the catalog."""

from typing import Literal


TextVariant = Literal["h1", "h2", "h3", "h4", "h5", "caption", "body"]
ImageFit = Literal["contain", "cover", "fill", "none", "scaleDown"]
ImageVariant = Literal["icon", "avatar", "smallFeature", "mediumFeature", "largeFeature", "header"]
IconName = Literal["accountCircle", "add", "arrowBack", "arrowForward", "attachFile", "calendarToday", "call", "camera", "check", "close", "delete", "download", "edit", "event", "error", "fastForward", "favorite", "favoriteOff", "folder", "help", "home", "info", "locationOn", "lock", "lockOpen", "mail", "menu", "moreVert", "moreHoriz", "notificationsOff", "notifications", "pause", "payment", "person", "phone", "photo", "play", "print", "refresh", "rewind", "search", "send", "settings", "share", "shoppingCart", "skipNext", "skipPrevious", "star", "starHalf", "starOff", "stop", "upload", "visibility", "visibilityOff", "volumeDown", "volumeMute", "volumeOff", "volumeUp", "warning"]
FlexJustify = Literal["start", "center", "end", "spaceBetween", "spaceAround", "spaceEvenly", "stretch"]
FlexAlign = Literal["center", "end", "start", "stretch"]
ListDirection = Literal["vertical", "horizontal"]
ListAlign = Literal["start", "center", "end", "stretch"]
DividerAxis = Literal["horizontal", "vertical"]
ButtonVariant = Literal["default", "primary", "borderless"]
TextFieldVariant = Literal["longText", "number", "shortText", "obscured"]
ChoicePickerVariant = Literal["multipleSelection", "mutuallyExclusive"]
ChoicePickerDisplaystyle = Literal["checkbox", "chips"]

__all__ = ["TextVariant", "ImageFit", "ImageVariant", "IconName", "FlexJustify", "FlexAlign", "ListDirection", "ListAlign", "DividerAxis", "ButtonVariant", "TextFieldVariant", "ChoicePickerVariant", "ChoicePickerDisplaystyle"]
