# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Python code emitter generating typed A2UI component libraries."""

from pathlib import Path
from typing import Union

from a2ui.codegen.analyzer import AnalysedCatalog, AnalysedComponentApi, AnalysedFunctionApi
from a2ui.codegen.emitter.base import BaseEmitter
from a2ui.codegen.types import (
    ActionType,
    CheckRuleType,
    ComponentListType,
    ComponentRefType,
    DataBindingType,
    DynamicType,
    EnumType,
    ListType,
    MapType,
    PrimitiveKind,
    PrimitiveType,
    PropertyDescriptor,
    TypeDescriptor,
    UnionType,
)


def type_to_python(type_desc: TypeDescriptor) -> str:
    """Converts an algebraic TypeDescriptor into a Python type annotation string."""
    match type_desc:
        case PrimitiveType(kind=PrimitiveKind.STRING):
            return "str"
        case PrimitiveType(kind=PrimitiveKind.INTEGER):
            return "int"
        case PrimitiveType(kind=PrimitiveKind.FLOAT):
            return "float"
        case PrimitiveType(kind=PrimitiveKind.BOOLEAN):
            return "bool"
        case PrimitiveType(kind=PrimitiveKind.ANY):
            return "Any"
        case EnumType(name=name):
            return name
        case ComponentRefType():
            return "ComponentBuilderNode"
        case ComponentListType():
            return "Sequence[ComponentBuilderNode] | DynamicChildList"
        case DynamicType(inner=inner):
            inner_str = type_to_python(inner)
            return f"{inner_str} | DataBinding | FunctionCall"
        case ActionType():
            return "Action"
        case DataBindingType():
            return "DataBinding"
        case CheckRuleType():
            return "CheckRule"
        case ListType(element_type=elem):
            return f"Sequence[{type_to_python(elem)}]"
        case MapType(value_type=val):
            return f"Mapping[str, {type_to_python(val)}]"
        case UnionType(options=opts):
            return " | ".join(type_to_python(o) for o in opts)
        case _:
            return "Any"


PYTHON_KEYWORDS = {
    "and",
    "as",
    "assert",
    "async",
    "await",
    "break",
    "class",
    "continue",
    "def",
    "del",
    "elif",
    "else",
    "except",
    "finally",
    "for",
    "from",
    "global",
    "if",
    "import",
    "in",
    "is",
    "lambda",
    "nonlocal",
    "not",
    "or",
    "pass",
    "raise",
    "return",
    "try",
    "while",
    "with",
    "yield",
}


def sanitize_ident(name: str) -> str:
    """Escapes names that collide with Python reserved keywords."""
    if name in PYTHON_KEYWORDS:
        return f"{name}_"
    return name


class PythonEmitter(BaseEmitter):
    """Emits complete, typed Python packages for A2UI catalogs."""

    def emit(self, output_dir: Union[str, Path]) -> list[Path]:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        written: list[Path] = []

        # 1. Emit types.py
        types_path = out / "types.py"
        types_path.write_text(self._generate_types(), encoding="utf-8")
        written.append(types_path)

        # 2. Emit components.py
        comp_path = out / "components.py"
        comp_path.write_text(self._generate_components(), encoding="utf-8")
        written.append(comp_path)

        # 3. Emit functions.py
        fn_path = out / "functions.py"
        fn_path.write_text(self._generate_functions(), encoding="utf-8")
        written.append(fn_path)

        # 4. Emit __init__.py
        init_path = out / "__init__.py"
        init_path.write_text(self._generate_init(), encoding="utf-8")
        written.append(init_path)

        # 5. Emit py.typed marker
        typed_path = out / "py.typed"
        typed_path.write_text("", encoding="utf-8")
        written.append(typed_path)

        return written

    def _generate_types(self) -> str:
        lines: list[str] = [
            "# Generated by a2ui-codegen. DO NOT EDIT DIRECTLY.",
            '"""String literal enums for the catalog."""',
            "",
            "from typing import Literal",
            "",
            "",
        ]

        for enum_name, enum_desc in self.catalog.enums.items():
            vals = ", ".join(f'"{v}"' for v in enum_desc.values)
            lines.append(f"{enum_name} = Literal[{vals}]")

        lines.append("")
        all_exports = ", ".join(f'"{e}"' for e in self.catalog.enums.keys())
        lines.append(f"__all__ = [{all_exports}]")
        lines.append("")
        return "\n".join(lines)

    def _generate_components(self) -> str:
        lines: list[str] = [
            "# Generated by a2ui-codegen. DO NOT EDIT DIRECTLY.",
            '"""Typesafe A2UI component definitions."""',
            "",
            "from dataclasses import dataclass, field",
            "from typing import Any, Mapping, Optional, Sequence, Union",
            "",
            f"from {self.base_import} import (",
            "    Action,",
            "    CheckRule,",
            "    ComponentBuilderNode,",
            "    DataBinding,",
            "    DynamicChildList,",
            "    FunctionCall,",
            ")",
            "from .types import *",
            "",
            "",
        ]

        for comp in self.catalog.components.values():
            lines.append(self._generate_component_class(comp))
            lines.append("")

        comp_names = [f'"{c}"' for c in self.catalog.components.keys()]
        lines.append(f"__all__ = [{', '.join(comp_names)}]")
        lines.append("")
        return "\n".join(lines)

    def _generate_component_class(self, comp: AnalysedComponentApi) -> str:
        lines: list[str] = [
            "@dataclass(kw_only=True)",
            f"class {comp.name}(ComponentBuilderNode):",
        ]

        # Docstring
        doc = comp.description or f"{comp.name} component."
        lines.append(f'    r"""{doc}"""')
        lines.append("")
        lines.append(f'    component_name: str = field(default="{comp.name}", init=False)')

        # Properties
        for p_name, prop in comp.properties.items():
            if p_name == "component":
                continue
            py_name = sanitize_ident(p_name)
            py_type = type_to_python(prop.type_desc)
            if prop.required:
                lines.append(f"    {py_name}: {py_type}")
            else:
                default_str = "None"
                if prop.default_value is not None:
                    if isinstance(prop.default_value, str):
                        default_str = f'"{prop.default_value}"'
                    elif isinstance(prop.default_value, bool):
                        default_str = str(prop.default_value)
                    elif isinstance(prop.default_value, (int, float)):
                        default_str = str(prop.default_value)
                lines.append(f"    {py_name}: Optional[{py_type}] = {default_str}")

        lines.append("")
        # to_dict method
        lines.append("    def to_dict(self) -> dict[str, Any]:")
        lines.append('        d: dict[str, Any] = {"component": self.component_name}')
        for p_name in comp.properties.keys():
            if p_name in ("component", "id"):
                continue
            py_name = sanitize_ident(p_name)
            lines.append(f"        if self.{py_name} is not None:")
            lines.append(
                f'            d["{p_name}"] = self.{py_name}.to_dict() if hasattr(self.{py_name}, "to_dict") else self.{py_name}'
            )

        lines.append("        if self.id is not None:")
        lines.append('            d["id"] = self.id')
        lines.append("        return d")

        return "\n".join(lines)

    def _generate_functions(self) -> str:
        lines: list[str] = [
            "# Generated by a2ui-codegen. DO NOT EDIT DIRECTLY.",
            '"""Typesafe catalog function wrappers."""',
            "",
            "from typing import Any, Mapping, Optional, Sequence, Union",
            "",
            f"from {self.base_import} import DataBinding, FunctionCall",
            "from .types import *",
            "",
            "",
        ]

        for fn in self.catalog.functions.values():
            lines.append(self._generate_function_def(fn))
            lines.append("")

        fn_names = [f'"{sanitize_ident(f)}"' for f in self.catalog.functions.keys()]
        lines.append(f"__all__ = [{', '.join(fn_names)}]")
        lines.append("")
        return "\n".join(lines)

    def _generate_function_def(self, fn: AnalysedFunctionApi) -> str:
        param_sigs: list[str] = ["*"]
        args_dict_items: list[str] = []
        py_fn_name = sanitize_ident(fn.name)

        for p_name, p_desc in fn.parameters.items():
            py_param = sanitize_ident(p_name)
            py_type = type_to_python(p_desc.type_desc)
            if p_desc.required:
                param_sigs.append(f"{py_param}: {py_type}")
            else:
                param_sigs.append(f"{py_param}: Optional[{py_type}] = None")
            args_dict_items.append(
                f'    if {py_param} is not None:\n'
                f'        args["{p_name}"] = {py_param}.to_dict() if hasattr({py_param}, "to_dict") else {py_param}'
            )

        param_sigs.append("call_id: Optional[str] = None")
        params_str = ", ".join(param_sigs)

        doc = fn.description or f"Invokes catalog function {fn.name}."
        lines: list[str] = [
            f"def {py_fn_name}({params_str}) -> FunctionCall:",
            f'    r"""{doc}"""',
            "    args: dict[str, Any] = {}",
        ]
        if args_dict_items:
            lines.append("\n".join(args_dict_items))
        lines.append(
            f'    return FunctionCall(call="{fn.name}", args=args, call_id=call_id)'
        )

        return "\n".join(lines)

    def _generate_init(self) -> str:
        lines: list[str] = [
            "# Generated by a2ui-codegen. DO NOT EDIT DIRECTLY.",
            '"""A2UI Typesafe Catalog package."""',
            "",
            f"from {self.base_import} import (",
            "    Action,",
            "    CheckRule,",
            "    ComponentBuilderNode,",
            "    ComponentRef,",
            "    DataBinding,",
            "    DynamicChildList,",
            "    ExternalComponentBuilderNode,",
            "    FunctionCall,",
            "    IdAllocator,",
            "    Surface,",
            "    bind,",
            "    flatten_component_tree,",
            ")",
            "from .components import *",
            "from .functions import *",
            "from .types import *",
            "",
        ]
        return "\n".join(lines)
