/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** The types of a React catalog entry and of what its rendering entry points receive. */

import type React from 'react';
import type {ComponentApi, ComponentContext, ComponentNode} from '@a2ui/web_core/v0_9';

/** Renders a resolved child node, or falls back for an unresolved id. */
export type NodeBuildChild = (
  child: ComponentNode<ReactComponentImplementation> | string,
  basePath?: string,
) => React.ReactNode;

/** What a component implementation's `view` receives from the node surface. */
export type NodeViewProps = {
  node: ComponentNode<ReactComponentImplementation>;
  buildChild: NodeBuildChild;
};

export interface ReactComponentImplementation extends ComponentApi {
  /** The framework-specific rendering wrapper. */
  render: React.FC<{
    context: ComponentContext;
    buildChild: (id: string, basePath?: string) => React.ReactNode;
  }>;
  /**
   * Renders this component from a resolved `ComponentNode`. Generated by the
   * factories in `adapter.tsx`. When absent, `A2uiSurface` renders through
   * `render`, handing it a `buildChild` that resolves ids through the node
   * layer.
   */
  view?: React.FC<NodeViewProps>;
}

export type ReactA2uiComponentProps<T> = {
  props: T;
  buildChild: (id: string, basePath?: string) => React.ReactNode;
  context: ComponentContext;
};
