// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// Copies the specification's `common_types.json` into Dart source, so the
/// published package carries the shared type definitions instead of asking
/// every caller to supply them.
///
/// Run from the package directory after editing the specification:
///
/// ```sh
/// dart run tool/generate_common_types.dart
/// ```
///
/// `test/common_types_test.dart` fails if the checked-in output has drifted
/// from the specification.
library;

import 'dart:io';

/// The specification files to copy, relative to the repository root, keyed by
/// the Dart constant each is embedded as.
const Map<String, String> sources = {
  'commonTypesV0_9Json': 'specification/v0_9/json/common_types.json',
  'commonTypesV1_0Json': 'specification/v1_0/json/common_types.json',
};

/// The file to write, relative to the package directory.
const String output = 'lib/src/validation/common_types.g.dart';

void main() {
  File(output).writeAsStringSync(
    render({
      for (final MapEntry<String, String> entry in sources.entries)
        entry.key: readSource(entry.value),
    }),
  );
  stdout.writeln('Wrote $output from ${sources.values.join(', ')}.');
}

/// Reads [source], searching upwards for the repository root so the tool runs
/// from the package directory or the workspace root.
String readSource(String source) {
  Directory dir = Directory.current;
  while (true) {
    final candidate = File('${dir.path}/$source');
    if (candidate.existsSync()) return candidate.readAsStringSync();
    final Directory parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError(
        'Could not find $source above ${Directory.current.path}.',
      );
    }
    dir = parent;
  }
}

/// Wraps each document in [documents], keyed by constant name, in a Dart
/// library, verbatim, so the generated file diffs against the specification
/// one line at a time.
///
/// Each document is embedded as a raw multiline string, which reproduces `$`
/// and `\` without escaping. Throws if a document is not expressible that
/// way, so a specification edit cannot silently produce a file that says
/// something other than what it copied.
String render(Map<String, String> documents) {
  final buffer = StringBuffer('''
// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by tool/generate_common_types.dart. Do not edit by hand.
//
// Verbatim copies of:
${sources.values.map((s) => '// - $s').join('\n')}
''');
  for (final MapEntry<String, String> entry in documents.entries) {
    final String source = sources[entry.key]!;
    final String json = entry.value;
    if (json.contains("'''")) {
      throw StateError("$source contains ''', which ends the string literal.");
    }
    if (json.endsWith("'")) {
      throw StateError("$source ends with ', which extends the delimiter.");
    }
    if (!json.startsWith('{')) {
      throw StateError('$source does not start with a JSON object.');
    }
    final String version =
        RegExp(r'specification/(v[0-9_]+)/').firstMatch(source)![1]!;
    buffer.write('''

/// The `common_types.json` document for protocol ${version.replaceAll('_', '.')}, as published.
const String ${entry.key} = r\'\'\'
$json\'\'\';
''');
  }
  return buffer.toString();
}
